### ISSUE TITLE
decrypt throws No data (GPGME::Error::NoData)

### ISSUE THREAD

**Issue by thomasmckay** [ueno/ruby-gpgme#117]
Running ruby-2.4.1 on centos7 VM. I am struggling to get the content. Perhaps I am misunderstanding how this should work.

```
GPGME::Engine.info
=> [#<GPGME::EngineInfo:0x00000002ac4c28 @file_name="/usr/bin/gpg2", @protocol=0, @req_version="1.4.0", @version="2.0.22">,
 #<GPGME::EngineInfo:0x00000002ac4728 @file_name="/usr/bin/gpgsm", @protocol=1, @req_version="2.0.4", @version="2.0.22">,
 #<GPGME::EngineInfo:0x00000002ac4278 @file_name="/usr/bin/gpgconf", @protocol=2, @req_version="2.0.4", @version="2.0.22">,
 #<GPGME::EngineInfo:0x00000002ac6bb8 @file_name="/home/vagrant/.gnupg/S.gpg-agent", @home_dir="!GPG_AGENT", @protocol=3, @req_version="1.0.0", @version="1.0.0">,
 #<GPGME::EngineInfo:0x00000002ac3c10 @file_name="/home/vagrant/.gnupg/S.uiserver", @protocol=5, @req_version="1.0.0", @version="1.0.0">,
 #<GPGME::EngineInfo:0x00000002ac31e8 @file_name="/nonexistent", @protocol=6, @req_version="1.0.0", @version="1.0.0">]
```
Script
```
#!/usr/bin/env ruby

require 'open-uri'
require 'gpgme'

open('https://www.redhat.com/security/fd431d51.txt') do |f|
  GPGME::Key.import(f)
end

crypto = GPGME::Crypto.new
open('https://access.redhat.com/webassets/docker/content/sigstore/rhel7/etcd@sha256=35fdf949dd7698ab5def00c504293be5fb5a5af29066a6e1684cf81a80bd6ce2/signature-1') do |f|
  crypto.decrypt(f)
end
```

Error is
```
/home/vagrant/.rvm/gems/ruby-2.4.1/gems/gpgme-2.0.16/lib/gpgme/ctx.rb:435:in `decrypt_verify': No data (GPGME::Error::NoData)
	from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/gpgme-2.0.16/lib/gpgme/crypto.rb:172:in `block in decrypt'
	from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/gpgme-2.0.16/lib/gpgme/ctx.rb:79:in `new'
	from /home/vagrant/.rvm/gems/ruby-2.4.1/gems/gpgme-2.0.16/lib/gpgme/crypto.rb:170:in `decrypt'
	from ./signature.rb:14:in `block in <main>'
	from /home/vagrant/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open-uri.rb:155:in `open_uri'
	from /home/vagrant/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open-uri.rb:721:in `open'
	from /home/vagrant/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open-uri.rb:35:in `open'
	from ./signature.rb:13:in `<main>'
```

From command line
```
$ gpg -d ../tmp/rhel7-etcd.sig 
{"critical": {"image": {"docker-manifest-digest": "sha256:35fdf949dd7698ab5def00c504293be5fb5a5af29066a6e1684cf81a80bd6ce2"}, "type": "atomic container signature", "identity": {"docker-reference": "registry.access.redhat.com/rhel7/etcd:latest"}}, "optional": {"creator": "Red Hat RCM Pub 0.21.0-final "}}gpg: Signature made Wed 07 Mar 2018 10:25:06 AM UTC using RSA key ID FD431D51
gpg: Good signature from "Red Hat, Inc. (release key 2) <security@redhat.com>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 567E 347A D004 4ADE 55BA  8A5F 199E 2F91 FD43 1D51
```

**Comment by thomasmckay** [comment]
I think this is user error: The file I'm verifying is encoded in something. I can verify the signature w/ GPGME but then need to decode (not decrypt) the file itself.

**Comment by thomasmckay** [comment]
```
uncompressed = crypto.verify(encrypted) {|signature| ...}
```
The uncompressed value is returned by crypto.verify.
