### ISSUE TITLE
Misleading error when trying to use :passphrase_callback with GnuPG 2.0.x

### ISSUE THREAD

**Issue by f3ndot** [ueno/ruby-gpgme#31]
Right now I'm attempting to develop an application using `ruby-gpgme` (at commit fd1d6b09d1b169ae433a4f4b4e2389f5c954bf8c). Here is your example sign, using the passphrase callback:

``` ruby
#!/usr/bin/env ruby
# test_sign.rb
require 'gpgme'

def passfunc(hook, uid_hint, passphrase_info, prev_was_bad, fd)
  $stderr.write("Passphrase for #{uid_hint}: ")
  $stderr.flush
  begin
    system('stty -echo')
    io = IO.for_fd(fd, 'w')
    io.puts(gets)
    io.flush
  ensure
    (0 ... $_.length).each do |i| $_[i] = ?0 end if $_
    system('stty echo')
  end
  $stderr.puts
end

crypto = GPGME::Crypto.new
signature = crypto.clearsign('test test test', {
                               :signer => '0xDEADBEEF',
                               :passphrase_callback => method(:passfunc)
                             })
puts signature.read
```

However when I'm using GnuPG version 2.0.x:

```
$ gpg --version
gpg (GnuPG/MacGPG2) 2.0.22
libgcrypt 1.5.3
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ?, ?
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

I get this horribly misleading error when trying to set the callback:

```
$ bundle exec ruby test_sign.rb
/Users/justinbull/.rvm/gems/ruby-2.0.0-p247/bundler/gems/ruby-gpgme-fd1d6b09d1b1/lib/gpgme/ctx.rb:438:in `sign': Bad passphrase (GPGME::Error::BadPassphrase)
    from /Users/justinbull/.rvm/gems/ruby-2.0.0-p247/bundler/gems/ruby-gpgme-fd1d6b09d1b1/lib/gpgme/crypto.rb:249:in `block in sign'
    from /Users/justinbull/.rvm/gems/ruby-2.0.0-p247/bundler/gems/ruby-gpgme-fd1d6b09d1b1/lib/gpgme/ctx.rb:71:in `new'
    from /Users/justinbull/.rvm/gems/ruby-2.0.0-p247/bundler/gems/ruby-gpgme-fd1d6b09d1b1/lib/gpgme/crypto.rb:242:in `sign'
    from /Users/justinbull/.rvm/gems/ruby-2.0.0-p247/bundler/gems/ruby-gpgme-fd1d6b09d1b1/lib/gpgme/crypto.rb:331:in `clearsign'
    from test_sign.rb:28:in `<main>'
```

I don't know what you can do to alleviate this error, but perhaps detect the version is 2.0.x and say that the `:passphrase_callback` logic is not supported?

_An aside:_

Using GnuPG 2.0.x, what's the best method to programatically sign some data? That is, without a human typing in the passphrase of a private key?

**Comment by ericdfields** [comment]
Seems like by now the 2.x line of gpg should have a way to do this. Is there no solution?
