### ISSUE TITLE
Invalid crypto engine (GPGME::Error::InvalidEngine)

### ISSUE THREAD

**Issue by rietta** [ueno/ruby-gpgme#42]
I am getting the **Invalid crypto engine (GPGME::Error::InvalidEngine)** error in my attempts to use the GPGME class.

This is on Mac OS X with `gpg`, `gpgme`, and `gpg-agent` installed.  Command-line GPG works fine.

What am I missing?
It installs cleanly:
`gem install gpgme`

```
Fetching: gpgme-2.0.5.gem (100%)
Building native extensions.  This could take a while...
Successfully installed gpgme-2.0.5
Parsing documentation for gpgme-2.0.5
Installing ri documentation for gpgme-2.0.5
Done installing documentation for gpgme after 3 seconds
1 gem installed
```

Then trying to run even one of the example scripts:
`ruby keylist.rb`

```
/Users/frank/.rvm/gems/ruby-2.1.1/gems/gpgme-2.0.5/lib/gpgme/ctx.rb:238:in `keylist_start': Invalid crypto engine (GPGME::Error::InvalidEngine)
    from /Users/frank/.rvm/gems/ruby-2.1.1/gems/gpgme-2.0.5/lib/gpgme/ctx.rb:269:in `each_key'
    from keylist.rb:5:in `<main>'
```

**Comment by do11** [comment]
Same problem. Used 2.0.2 w/o any problem, then after gem update to 2.0.8 got this error with any operation.
```
$ GPGME_DEBUG=9 irb
irb-f(main):001:0> require 'gpgme'
GPGME 2015-04-03 09:44:37 <0x7703>  gpgme_debug: level=9
GPGME 2015-04-03 09:44:37 <0x7703>  gpgme_check_version: call: 0=(nil), req_version=(null), VERSION=1.5.3
GPGME 2015-04-03 09:44:37 <0x7703>  gpgme_check_version_internal: call: 0=(nil), req_version=(null), offset_sig_validity=32
=> true
irb-f(main):002:0> GPGME::Key.find('testkey@test.com')
GPGME 2015-04-03 09:44:41 <0x7703>  gpgme_new: enter: r_ctx=0xbf8bb63c
GPGME 2015-04-03 09:44:41 <0x7703>  gpgme-dinfo: gpgconf='/usr/bin/gpgconf'
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_pipe: enter: filedes=0xbf8bb060, inherit_idx=1 (GPGME uses it for reading)
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_pipe: leave: read=0x5, write=0x6
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_spawn: enter: path=0x854b7e0, path=/usr/bin/gpgconf
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_spawn: check: path=0x854b7e0, argv[ 0] = /usr/bin/gpgconf
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_spawn: check: path=0x854b7e0, argv[ 1] = --list-dirs
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_spawn: check: path=0x854b7e0, fd[0] = 0x6 -> 0x1
GPGME 2015-04-03 09:44:41 <0x7709>      gpgme:max_fds: call: 0=(nil), max fds=1024 (RLIMIT_NOFILE)
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_spawn: check: path=0x854b7e0, waiting for child process pid=30472
GPGME 2015-04-03 09:44:41 <0x7703>      _gpgme_io_close: enter: fd=0x6
GPGME 2015-04-03 09:44:41 <0x7703>      _gpgme_io_close: leave: result=0
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_spawn: leave: result=0
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_read: enter: fd=0x5, buffer=0xbf8bb074, count=1023
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_read: leave: result=0
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_close: enter: fd=0x5
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_close: leave: result=0
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_pipe: enter: filedes=0xbf8bb060, inherit_idx=1 (GPGME uses it for reading)
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_pipe: leave: read=0x5, write=0x6
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_spawn: enter: path=0x854b7e0, path=/usr/bin/gpgconf
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_spawn: check: path=0x854b7e0, argv[ 0] = /usr/bin/gpgconf
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_spawn: check: path=0x854b7e0, argv[ 1] = --list-components
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_spawn: check: path=0x854b7e0, fd[0] = 0x6 -> 0x1
GPGME 2015-04-03 09:44:41 <0x770b>      gpgme:max_fds: call: 0=(nil), max fds=1024 (RLIMIT_NOFILE)
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_spawn: check: path=0x854b7e0, waiting for child process pid=30474
GPGME 2015-04-03 09:44:41 <0x7703>      _gpgme_io_close: enter: fd=0x6
GPGME 2015-04-03 09:44:41 <0x7703>      _gpgme_io_close: leave: result=0
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_spawn: leave: result=0
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_read: enter: fd=0x5, buffer=0xbf8bb074, count=1023
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_read: check: 6770673a47504720 666f72204f70656e gpg:GPG for Open
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_read: check: 5047500a6770672d 6167656e743a4750 PGP.gpg-agent:GP
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_read: check: 47204167656e740a 73636461656d6f6e G Agent.scdaemon
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_read: check: 3a536d6172746361 7264204461656d6f :Smartcard Daemo
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_read: check: 6e0a677067736d3a 47504720666f7220 n.gpgsm:GPG for
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_read: check: 532f4d494d450a64 69726d6e67723a44 S/MIME.dirmngr:D
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_read: check: 69726563746f7279 204d616e61676572 irectory Manager
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_read: check: 0a                                .
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_read: leave: result=113
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_read: enter: fd=0x5, buffer=0xbf8bb074, count=1023
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_read: leave: result=0
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_close: enter: fd=0x5
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_close: leave: result=0
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_pipe: enter: filedes=0xbf8bb450, inherit_idx=1 (GPGME uses it for reading)
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_pipe: leave: read=0x5, write=0x6
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_spawn: enter: path=0x854b7e0, path=/usr/bin/gpgconf
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_spawn: check: path=0x854b7e0, argv[ 0] = /usr/bin/gpgconf
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_spawn: check: path=0x854b7e0, argv[ 1] = --version
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_spawn: check: path=0x854b7e0, fd[0] = 0x6 -> 0x1
GPGME 2015-04-03 09:44:41 <0x770d>      gpgme:max_fds: call: 0=(nil), max fds=1024 (RLIMIT_NOFILE)
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_spawn: check: path=0x854b7e0, waiting for child process pid=30476
GPGME 2015-04-03 09:44:41 <0x7703>      _gpgme_io_close: enter: fd=0x6
GPGME 2015-04-03 09:44:41 <0x7703>      _gpgme_io_close: leave: result=0
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_spawn: leave: result=0
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_read: enter: fd=0x5, buffer=0xbf8bb458, count=79
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_read: check: 677067636f6e6620 28476e7550472920 gpgconf (GnuPG)
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_read: check: 322e302e340a436f 7079726967687420 2.0.4.Copyright
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_read: check: 2843292032303037 204672656520536f (C) 2007 Free So
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_read: check: 6674776172652046 6f756e646174696f ftware Foundatio
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_read: check: 6e2c20496e632e0a 54686973207072   n, Inc..This pr
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_read: leave: result=79
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_close: enter: fd=0x5
GPGME 2015-04-03 09:44:41 <0x7703>    _gpgme_io_close: leave: result=0
GPGME 2015-04-03 09:44:41 <0x7703>  gpgme_new: leave: ctx=0x84cf758
GPGME 2015-04-03 09:44:41 <0x7703>  gpgme_op_keylist_start: enter: ctx=0x84cf758, pattern=, secret_only=0
GPGME 2015-04-03 09:44:41 <0x7703>  gpgme_op_keylist_start:901: error: Unsupported protocol <GPGME>
GPGME 2015-04-03 09:44:41 <0x7703>  gpgme_release: call: ctx=0x84cf758
GPGME::Error: GPGME::Error
        from /usr/local/lib/ruby/gems/1.9.1/gems/gpgme-2.0.8/lib/gpgme/ctx.rb:238:in `keylist_start'
        from /usr/local/lib/ruby/gems/1.9.1/gems/gpgme-2.0.8/lib/gpgme/ctx.rb:269:in `each_key'
        from /usr/local/lib/ruby/gems/1.9.1/gems/gpgme-2.0.8/lib/gpgme/ctx.rb:284:in `keys'
        from /usr/local/lib/ruby/gems/1.9.1/gems/gpgme-2.0.8/lib/gpgme/key.rb:57:in `block (2 levels) in find'
        from /usr/local/lib/ruby/gems/1.9.1/gems/gpgme-2.0.8/lib/gpgme/ctx.rb:71:in `new'
        from /usr/local/lib/ruby/gems/1.9.1/gems/gpgme-2.0.8/lib/gpgme/key.rb:56:in `block in find'
        from /usr/local/lib/ruby/gems/1.9.1/gems/gpgme-2.0.8/lib/gpgme/key.rb:52:in `each'
        from /usr/local/lib/ruby/gems/1.9.1/gems/gpgme-2.0.8/lib/gpgme/key.rb:52:in `find'
        from (irb):2
        from /usr/local/bin/irb:12:in `<main>'
```

**Comment by ueno** [comment]
glad that we've finally got the log. I think GPGME (the C library) should report a better error message in that case, though your GnuPG version is way too old. if you have working GPGME installed on system, a work around would be: gem install gpgme -- --use-system-libraries

**Comment by do11** [comment]
Thanks. I can't install with `--use-system-libraries` because of `ERROR: Failed to build gem native extension.` (`checking for gpgme >= 1.1.3... *** extconf.rb failed ***`. `gpgme-config --version` is `1.1.4`.) But, maybe it will be useful for someone else with the same issue. I'm personally rolled back to [ruby-]gpgme 2.0.2.
