### ISSUE TITLE
Cannot install on OS X 10.10(.1)

### ISSUE THREAD

**Issue by zykadelic** [ueno/ruby-gpgme#55]
Install is complaining about "*You have to install development tools first.*", but development tools is already installed and up to date.
* xcode 6.1.1 (6A2008a)
* xquartz 2.7.7 (xorg-server 1.15.2)
* rvm 1.25.29
* ruby 1.9.3p547
* rails 3.2.13
* gpgme-2.0.7

```bash
$ brew doctor
Your system is ready to brew.
```

```bash
$ gem install gpgme
Building native extensions.  This could take a while...
ERROR:  Error installing gpgme:
	ERROR: Failed to build gem native extension.

    /Users/zykadelic/.rvm/rubies/ruby-1.9.3-p547/bin/ruby extconf.rb
************************************************************************
IMPORTANT!  gpgme gem uses locally built versions of required C libraries,
namely libgpg-error, libassuan, and gpgme.

If this is a concern for you and you want to use the system library
instead, abort this installation process and reinstall gpgme gem as
follows:

    gem install gpgme -- --use-system-libraries

************************************************************************
sh: line 1: 47984 Segmentation fault: 11  /usr/local/opt/gcc46/bin/gcc-4.6 -v 2>&1
Extracting libgpg-error-1.13.tar.bz2 into tmp//ports/libgpg-error/1.13... OK
Running 'configure' for libgpg-error 1.13... OK
Running 'compile' for libgpg-error 1.13... OK
Running 'install' for libgpg-error 1.13... OK
Activating libgpg-error 1.13 (from /Users/zykadelic/.rvm/gems/ruby-1.9.3-p547/gems/gpgme-2.0.7/ports//libgpg-error/1.13)...
sh: line 1: 51364 Segmentation fault: 11  /usr/local/opt/gcc46/bin/gcc-4.6 -v 2>&1
Extracting libassuan-2.1.2.tar.bz2 into tmp//ports/libassuan/2.1.2... OK
Running 'configure' for libassuan 2.1.2... OK
Running 'compile' for libassuan 2.1.2... OK
Running 'install' for libassuan 2.1.2... OK
Activating libassuan 2.1.2 (from /Users/zykadelic/.rvm/gems/ruby-1.9.3-p547/gems/gpgme-2.0.7/ports//libassuan/2.1.2)...
sh: line 1: 54987 Segmentation fault: 11  /usr/local/opt/gcc46/bin/gcc-4.6 -v 2>&1
Extracting gpgme-1.5.1.tar.bz2 into tmp//ports/gpgme/1.5.1... OK
Running 'configure' for gpgme 1.5.1... OK
Running 'compile' for gpgme 1.5.1... OK
Running 'install' for gpgme 1.5.1... OK
Activating gpgme 1.5.1 (from /Users/zykadelic/.rvm/gems/ruby-1.9.3-p547/gems/gpgme-2.0.7/ports//gpgme/1.5.1)...
checking for linker flags for static linking... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/zykadelic/.rvm/rubies/ruby-1.9.3-p547/bin/ruby
	--clean
	--use-system-libraries
/Users/zykadelic/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:381:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Users/zykadelic/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:461:in `try_link0'
	from /Users/zykadelic/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:476:in `try_link'
	from extconf.rb:159:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/zykadelic/.rvm/gems/ruby-1.9.3-p547/gems/gpgme-2.0.7 for inspection.
Results logged to /Users/zykadelic/.rvm/gems/ruby-1.9.3-p547/extensions/x86_64-darwin-13/1.9.1/gpgme-2.0.7/gem_make.out
```

```bash
$ gem install gpgme -- --use-system-libraries
Building native extensions with: '--use-system-libraries'
This could take a while...
ERROR:  Error installing gpgme:
	ERROR: Failed to build gem native extension.

    /Users/zykadelic/.rvm/rubies/ruby-1.9.3-p547/bin/ruby extconf.rb --use-system-libraries
checking for gpgme-config... yes
checking for gpgme >= 1.1.3... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/zykadelic/.rvm/rubies/ruby-1.9.3-p547/bin/ruby
	--clean
	--use-system-libraries
/Users/zykadelic/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:381:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Users/zykadelic/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:461:in `try_link0'
	from /Users/zykadelic/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:712:in `try_run'
	from extconf.rb:185:in `block in <main>'
	from /Users/zykadelic/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:790:in `block in checking_for'
	from /Users/zykadelic/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:284:in `block (2 levels) in postpone'
	from /Users/zykadelic/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:254:in `open'
	from /Users/zykadelic/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:284:in `block in postpone'
	from /Users/zykadelic/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:254:in `open'
	from /Users/zykadelic/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:280:in `postpone'
	from /Users/zykadelic/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:789:in `checking_for'
	from extconf.rb:184:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/zykadelic/.rvm/gems/ruby-1.9.3-p547/gems/gpgme-2.0.7 for inspection.
Results logged to /Users/zykadelic/.rvm/gems/ruby-1.9.3-p547/extensions/x86_64-darwin-13/1.9.1/gpgme-2.0.7/gem_make.out
```

**Comment by Purushotham233** [comment]
i faced similar issue. When I tried gcc -v , it was complaining xcode path is not available. 

$gcc -v
xcrun: error: active developer path ("/Volumes/Xcode/Xcode.app/Contents/Developer") does not exist, use `xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools (or see `man xcode-select`)

Then I tried to switch the path.
 $ sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

Check the path after changing path.
$xcode-select -p
/Applications/Xcode.app/Contents/Developer

**Comment by zykadelic** [comment]
Did it work for you after changing that? My Xcode install (now updated to 6.2 (6C131e)) seems fine:
```bash
$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix
$ xcode-select -p
/Applications/Xcode.app/Contents/Developer
```

Still running into the same error when trying to install the gem.

**Comment by sergderevyanko** [comment]
Have you resolved issue? I've faced with same and resolve it by execution 
    export GREP_OPTIONS='--color=never' 
and run gem install after that. 
In my case problem was caused by grep. It added special symbols for color matched pattern and  passed files for father processing. Disabling --color option for grep resolved problem.

**Comment by zykadelic** [comment]
Thanks for the tip @sergderevyanko, but I’m running into the same error after running `export GREP_OPTIONS='--color=never'`

**Comment by zykadelic** [comment]
Now installs just fine...
* OS X version 10.10.3
* xcode 6.3.1 (6D1002)
* xquartz 2.7.7 (xorg-server 1.15.2)
* rvm 1.26.11
* ruby 1.9.3p551
* rails 3.2.13
* gpgme-2.0.7

My guess is that xcode 6.3 fixed it.

**Comment by LucasArruda** [comment]
`brew install gpgme` fixes it too

**Comment by WtfJoke** [comment]
` gem install gpgme -- --use-system-libraries` <-- fixed it for me

**Comment by LucasArruda** [comment]
@WtfJoke this worked for me also last time I saw it (on a colleague's computer).
